<?php

namespace App\Helpers;

class Translator {
    private static ?array $dictionary = null;

    /**
     * Translate the HTML output buffer to Thai.
     */
    public static function translate(string $buffer): string {
        // Skip translating JSON responses, CSVs, or downloads to protect raw data structures
        foreach (headers_list() as $header) {
            if (stripos($header, 'Content-Type:') !== false) {
                if (stripos($header, 'application/json') !== false || stripos($header, 'text/csv') !== false || stripos($header, 'application/octet-stream') !== false) {
                    return $buffer;
                }
            }
        }

        if (self::$dictionary === null) {
            self::$dictionary = [
                'Computer Reservation System' => 'ระบบจองเครื่องคอมพิวเตอร์',
                'LabReserve' => 'ระบบจองห้องแล็บ',
                'Dashboard' => 'แผงควบคุม',
                'Reservations' => 'การจองเครื่อง',
                'Workstations' => 'เครื่องคอมพิวเตอร์',
                'Laboratories' => 'ห้องปฏิบัติการ',
                'User Accounts' => 'บัญชีผู้ใช้',
                'Usage Reports' => 'รายงานการใช้งาน',
                'System Settings' => 'ตั้งค่าระบบ',
                'Security Profile' => 'ความปลอดภัยโปรไฟล์',
                'Log Out' => 'ออกจากระบบ',
                'Logout' => 'ออกจากระบบ',
                'Notifications' => 'การแจ้งเตือน',
                'No new notifications.' => 'ไม่มีการแจ้งเตือนใหม่',
                'View Reservations History' => 'ดูประวัติการจองทั้งหมด',
                'Sign In' => 'เข้าสู่ระบบ',
                'Email Address' => 'ที่อยู่อีเมล',
                'Password' => 'รหัสผ่าน',
                'Remember this device' => 'จดจำอุปกรณ์นี้',
                'Forgot Password?' => 'ลืมรหัสผ่าน?',
                'Use default credentials to explore' => 'เข้าสู่ระบบด้วยบัญชีเริ่มต้นเพื่อทดสอบ',
                'Admin' => 'ผู้ดูแลระบบ',
                'Student' => 'นักศึกษา',
                'Reset Password' => 'รีเซ็ตรหัสผ่าน',
                'Recover your LabReserve account access' => 'กู้คืนการเข้าถึงบัญชีระบบจองห้องแล็บ',
                'Send Reset Instructions' => 'ส่งลิงก์รีเซ็ตรหัสผ่าน',
                'Back to Sign In' => 'กลับไปยังหน้าเข้าสู่ระบบ',
                'Create New Password' => 'สร้างรหัสผ่านใหม่',
                'Set a secure password for your account' => 'ตั้งรหัสผ่านที่ปลอดภัยสำหรับบัญชีของคุณ',
                'New Password' => 'รหัสผ่านใหม่',
                'Confirm Password' => 'ยืนยันรหัสผ่าน',
                'Save Password' => 'บันทึกรหัสผ่าน',
                'Cancel recovery?' => 'ยกเลิกการกู้คืน?',
                'Back to Login' => 'กลับไปยังหน้าล็อกอิน',
                'Workstations Free' => 'เครื่องว่างพร้อมใช้งาน',
                'Approved Seats' => 'การจองที่อนุมัติแล้ว',
                'Pending Review' => 'รอการตรวจสอบ',
                'Under Maintenance' => 'อยู่ระหว่างบำรุงรักษา',
                'Active and available for booking' => 'เปิดใช้งานและสามารถจองได้',
                'Confirmed schedules awaiting check-in' => 'ยืนยันกำหนดการจองแล้ว รอเข้าใช้งาน',
                'Requires administrator approval' => 'ต้องได้รับอนุมัติจากผู้ดูแลระบบ',
                'Offline workstations being serviced' => 'ปิดใช้งานเพื่อตรวจซ่อมบำรุงรักษา',
                'Reservation Schedule' => 'ตารางเวลาการจอง',
                'New Booking' => 'เพิ่มการจองใหม่',
                'Reservation Trends' => 'แนวโน้มการจอง',
                'Status Breakdown' => 'สัดส่วนตามสถานะ',
                'Helpful Instructions' => 'คำแนะนำที่เป็นประโยชน์',
                'Welcome to the Department Computer Lab Booking System.' => 'ยินดีต้อนรับสู่ระบบจองห้องปฏิบัติการคอมพิวเตอร์ภาควิชา',
                'Submit your reservations up to 1 week in advance.' => 'ส่งคำขอจองเครื่องล่วงหน้าได้สูงสุด 1 สัปดาห์',
                'Approved bookings must check in within 15 minutes of the start time.' => 'การจองที่อนุมัติแล้วต้องเช็คอินภายใน 15 นาทีหลังจากถึงเวลาเริ่มต้น',
                'Always remember to check out when you finish to release the computer for other students.' => 'อย่าลืมเช็คเอาท์ทุกครั้งหลังใช้งานเสร็จสิ้นเพื่อคืนเครื่องให้ผู้ใช้อื่น',
                'Make a Booking Now' => 'ทำการจองเครื่องทันที',
                'Most Booked Computers' => 'คอมพิวเตอร์ที่มียอดจองสูงสุด',
                'Workstation Code' => 'รหัสเครื่องคอมฯ',
                'Lab Room' => 'ห้องปฏิบัติการ',
                'Bookings Count' => 'จำนวนการจอง',
                'Recent Activities' => 'กิจกรรมล่าสุดของระบบ',
                'Search' => 'ค้นหา',
                'Status' => 'สถานะ',
                'Date' => 'วันที่',
                'Filter' => 'กรองข้อมูล',
                'My Bookings & Reservations' => 'รายการจองของฉัน',
                'Reserve Computer' => 'จองเครื่องคอมพิวเตอร์',
                'User Account' => 'บัญชีผู้ใช้',
                'Schedule Timing' => 'ตารางเวลาการจอง',
                'Actions' => 'การดำเนินการ',
                'View Reservation Details' => 'ดูรายละเอียดการจอง',
                'Check In Workstation' => 'เช็คอินเข้าใช้งาน',
                'Check Out Workstation' => 'เช็คเอาท์ออกจากการใช้งาน',
                'Cancel Booking' => 'ยกเลิกการจอง',
                'All Rooms' => 'ทุกห้องปฏิบัติการ',
                'All Statuses' => 'ทุกสถานะ',
                'Pending' => 'รออนุมัติ',
                'Approved' => 'อนุมัติแล้ว',
                'Rejected' => 'ปฏิเสธคำขอ',
                'Cancelled' => 'ยกเลิกแล้ว',
                'Completed' => 'เสร็จสิ้น',
                'Expired' => 'หมดเวลาเช็คอิน',
                'New Computer Reservation' => 'คำขอจองคอมพิวเตอร์ใหม่',
                'Back to List' => 'กลับไปยังหน้ารายการ',
                '1. Select Laboratory Room' => '1. เลือกห้องปฏิบัติการ',
                '2. Reservation Date' => '2. เลือกวันที่ต้องการจอง',
                'Start Time' => 'เวลาเริ่มต้น',
                'End Time' => 'เวลาสิ้นสุด',
                '3. Choose Available Workstation(s)' => '3. เลือกเครื่องคอมพิวเตอร์ที่ว่าง',
                'No available workstations found' => 'ไม่พบเครื่องคอมพิวเตอร์ที่ว่างในช่วงเวลานี้',
                '4. Purpose of Reservation' => '4. วัตถุประสงค์ในการจอง',
                'Submit Reservation' => 'ส่งคำขอจองเครื่อง',
                'Reservation Details' => 'รายละเอียดการจอง',
                'Submitted on' => 'ยื่นคำขอเมื่อ',
                'Reservist Details' => 'รายละเอียดผู้จอง',
                'Full Name' => 'ชื่อ-นามสกุล',
                'Student ID' => 'รหัสนักศึกษา',
                'Employee ID' => 'รหัสพนักงาน',
                'Location' => 'ที่ตั้งห้องแล็บ',
                'Duration' => 'ระยะเวลาใช้งาน',
                'Assigned Workstation' => 'เครื่องคอมพิวเตอร์ที่จัดสรรให้',
                'Asset ID' => 'รหัสครุภัณฑ์',
                'IP Address' => 'ที่อยู่ IP',
                'Processor' => 'หน่วยประมวลผล (CPU)',
                'RAM' => 'หน่วยความจำ (RAM)',
                'Storage' => 'ความจุ (Storage)',
                'Operating System' => 'ระบบปฏิบัติการ (OS)',
                'Checked In Time' => 'เวลาที่เช็คอิน',
                'Checked Out Time' => 'เวลาที่เช็คเอาท์',
                'Decision Log Details' => 'บันทึกการพิจารณาคำขอ',
                'Reviewed By' => 'ผู้ตรวจสอบโดย',
                'Remarks' => 'บันทึกข้อความ',
                'Approve Booking Request' => 'อนุมัติคำขอการจอง',
                'Decline Booking Request' => 'ปฏิเสธคำขอการจอง',
                'Confirm Approval' => 'ยืนยันอนุมัติ',
                'Reject Booking' => 'ปฏิเสธคำขอ',
                'Manage Workstations' => 'จัดการเครื่องคอมพิวเตอร์',
                'Print QR/Barcodes' => 'พิมพ์ฉลาก QR/Barcode',
                'Register Workstation' => 'ลงทะเบียนคอมพิวเตอร์ใหม่',
                'Device Info' => 'ข้อมูลตัวเครื่อง',
                'Room Location' => 'ห้องปฏิบัติการที่ตั้ง',
                'Manage Laboratories' => 'จัดการห้องปฏิบัติการ',
                'Register Laboratory' => 'ลงทะเบียนห้องแล็บใหม่',
                'Seat Capacity' => 'ความจุจำนวนที่นั่ง',
                'Manage User Accounts' => 'จัดการบัญชีผู้ใช้งาน',
                'Add User Account' => 'เพิ่มบัญชีผู้ใช้งานใหม่',
                'System Role' => 'สิทธิ์ระบบ',
                'Account Status' => 'สถานะบัญชี',
                'Usage & Reservations Analytics Reports' => 'รายงานวิเคราะห์ยอดใช้งานและการจอง',
                'Print Report' => 'พิมพ์รายงาน',
                'Export to Excel' => 'ส่งออกเป็นไฟล์ Excel',
                'Security Profile Settings' => 'ตั้งค่าความปลอดภัยบัญชี',
                'Current Password' => 'รหัสผ่านปัจจุบัน',
                'Confirm New Password' => 'ยืนยันรหัสผ่านใหม่',
                'Update Password' => 'อัปเดตรหัสผ่าน',
                'Database Backups' => 'สำรองข้อมูลฐานข้อมูล',
                'Download SQL Backup' => 'ดาวน์โหลดไฟล์สำรอง SQL',
                'Restore System Database' => 'กู้คืนระบบฐานข้อมูล',
                'Upload & Restore DB' => 'อัปโหลดและกู้คืน DB',
                'Return to Dashboard' => 'กลับสู่แผงควบคุม',
                'Internal Server Error' => 'ข้อผิดพลาดภายในระบบ',
                'Page Not Found' => 'ไม่พบหน้าที่คุณต้องการ',
            ];
        }

        // Apply translations using optimized strtr
        return strtr($buffer, self::$dictionary);
    }
}
